### ISSUE TITLE
alacritty has moved background_opacity setting into just opacity under window

### ISSUE THREAD

**Issue by HiMyNameIsGarch** [ysomad/dotfiles#2]
Alacritty has changed the setting for `background_opacity` under `window` with the name of just `opacity`.
Current alacritty config: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
Your [script](https://github.com/ysomad/dotfiles/blob/main/bin/toggle_alacritty_opacity) still uses the old setting and from what I've seen you're current [config](https://github.com/ysomad/dotfiles/blob/main/alacritty/alacritty.yml) is changed to the new one.

**Comment by ysomad** [comment]
Yeah, true. I'm at MacOS rn and didn't use this script since I switched from linux
